name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Install Pytest
            run: pip install pytest pytest-cov
          - name: Run pytest
            run: python -m pytest --cov-report xml:coverage.xml
          - name: Get Cover 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: cover.xml
                token: ${{ secrets.GITHUB_TOKEN }}